<a href="https://colab.research.google.com/github/MallikarjunPatil24/IT-ignite/blob/main/libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy: It, short for Numerical Python, is the core library for numerical and scientific computing in Python.

Pandas: It is a data analysis and manipulation library built on top of NumPy.

Matplotlib: It is a data visualization library that helps you create a wide variety of static, animated and interactive plots.

In [5]:
import numpy as np
m = np.array([[1,2,3],[2,4,6],[3,5,7]])
print(m)

[[1 2 3]
 [2 4 6]
 [3 5 7]]


In [23]:
a0 = np.zeros((4,4))
a1 = np.arange(0,3)
print('a1:',a1)
print('a0:',a0)

a1: [0 1 2]
a0: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
# Uncomment ONLY if running locally (not needed in Colab)
# !pip install numpy pandas matplotlib seaborn

import numpy as np                     # numerical computing
import pandas as pd                    # data manipulation
import matplotlib.pyplot as plt        # plotting
import matplotlib.patches as mpatches  # custom legend handles
import seaborn as sns                  # statistical visualization
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['axes.spines.top']   = False
plt.rcParams['axes.spines.right'] = False

print('All libraries imported successfully!')
print(f'  NumPy   {np.__version__}')
print(f'  Pandas  {pd.__version__}')
print(f'  Seaborn {sns.__version__}')

All libraries imported successfully!
  NumPy   2.0.2
  Pandas  2.2.2
  Seaborn 0.13.2
